name: vapor-master
version: '0.1'
grade: stable
confinement: strict
summary: RosHub Vapor Master
description: RosHub Vapor Master
architectures:
  - build-on: [amd64, i386]

apps:
  vapor-master:
    command: npx vapor-master
    plugs: [network, network-bind]
    daemon: simple

parts:
  vapor-master:
    source: .
    plugin: nodejs
    node-engine: "8.12.0"
    node-package-manager: "yarn"
